# Generated by Django 5.0.7 on 2024-07-27 18:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_company_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phoneNumber', models.CharField(max_length=100)),
                ('about', models.TextField()),
                ('designation', models.CharField(choices=[('Project Manager', 'Project Manager'), ('Junior Developer', 'Junior Developer'), ('Java Developer', 'Java Developer')], max_length=1000)),
                ('companyId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
    ]
