# Generated by Django 5.0.7 on 2024-07-27 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='companyId',
            new_name='company',
        ),
    ]
