# Generated by Django 5.0.7 on 2024-07-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_employee_id_employee_employeeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employeeId',
        ),
        migrations.AddField(
            model_name='employee',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
